### ISSUE TITLE
epic: post-prototype frontend foundation

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp-campaigns#210]
Currently, we have a working prototype which has served its purpose very well for the WCUS demonstration and will continue to do so until we release an alpha version.

Unfortunately, the prototype is too focused on the builder view and is structured in a way that does not account for other parts of the application or other contexts that the plugin will provide experiences for (i.e. campaigns outside of the builder). We need to shift a few things around in order to achieve the goals of the MVP, as well, change how we are managing the application state. 

Note that everything that is mentioned below has been confirmed to work already, it’s just a matter of implementing it all in our project.

## Frontend tasks

- [ ] Create _four_ necessary clients.
    1. _Admin_: This is the view we have most worked on already. It includes a dashboard for managing campaigns in bulk and the builder for creating/modifying a single campaign.
    2. _Landing_: This is the client for campaigns with landing pages.
    3. _Embed_: This is for if the user decides to embed a campaign.
    4. _Gutenberg Block_: This is for embedding the block within a page or post made in the Gutenberg editor. This might rely on the embed client internally.
- [ ] Use Context (and Apollo?) instead of Redux for state management.
    - [Colocating the state] for certain views and components makes the state management less complex. We can leverage hooks and the Context API for this.
    - I think it could be valuable to try and use Apollo Client as well. We don’t have a GraphQL backend (yet?), but we can use local resolvers with REST API requests/cache. @JasonTheAdams what do you think about this?
        - You can also easily mock a data source this way too, by caching static datasets.
- [ ] Switch `@givewp/components` to `@givewp/ui` and move client/component specific UI elements to their own namespace (i.e. subdirectory with exports) within this workspace.
    - `@givewp/ui/primitives` will have UI primitives that can either be used as the basis of the namespaced component libraries or they can be used standalone (i.e. layout primitives like `Stack`, `Grid`, can live here).
    - `@givewp/ui/admin` will have all of the UI components used by `@givewp/admin`, `@givewp/dashboard`, and `@givewp/builder`.
    - `@givewp/ui/campaign` will have all of the UI components used by `@givewp/campaign`.
    - Why not house these specific component in the workspaces that they are associated with? Since they are highly used within those workspaces, it is a bit of a pain to use relative paths to reference them.
- [ ] Use a form controller library for controlling form inputs/state in both the builder and the campaign.
    - This means we don’t have to pass `onChange` events for individual input fields. As well, the form can detect changes and dispatch them at the right time to update the preview.

### Admin client

For the most part, the admin client itself is an app shell with a (hash) router. Its state does not need to be complex: it should just have a control for whether it is nested in the WordPress admin UI or filling the viewport and it can also be used for caching common datasets between the Dashboard and the Builder.

- [ ] Move the Router to the top level of the app.
    - Currently, the router is for the campaign settings tabs, but really this should be controlled with a URL search param (or not at all).
    - `/dasboard` (default) and `/builder` will control what view is currently active. We can use URL search params to provide additional context for those views (e.g. `/dashboard?s=Pandas` would tell the dashboard to only list Campaigns that met that search requirement; `/builder?id=11a7c267-21d4-437c-956a-53575dcf8c5a` would open the builder for the corresponding Campaign).

[Colocating the state]: https://kentcdodds.com/blog/state-colocation-will-make-your-react-app-faster

#### Dashboard view

- [ ] Create a workspace `@givewp/dashboard` for this view
    * I think that it would be wise to separate this into its own workspace since the component often needs to interact with the admin context as well as its own and relative paths to wherever those context/hooks are stored can be a bit of a pain.
- [ ] Begin working on this view

#### Builder view

- [ ] Create a workspace `@givewp/builder` for this view
    - I think that it would be wise to separate this into its own workspace since the component often needs to interact with the admin context as well as its own and relative paths to wherever those context/hooks are stored can be a bit of a pain.
      ```js
      /**
       * Confusing
       * resources/js/admin/views/builder/components/SomeSubComponent.jsx
       */
      import {useAdminState} from '../../../context'
      import {useBuilderDispatch} from '../context';

      /**
       * Better
       * resources/js/builder/components/SomeSubComponent.jsx
       */
       import {useAdminState} from '@givewp/admin/context';
       import {useBuilderDispatch} from '../context';
      ```
- [ ] With the router moving to the top of the admin client, a different solution for the settings panels will need to be implmented. I suggest `@reach/tabs`.

### Campaign component

This is the component that needs the most work in my opinion. Currently, it does not work outside of the builder, so we will need to break it out and get it working on its own, but with enhancements when used within the builder context.

- [ ] Create a workspace `@givewp/campaign` for the component
    - This component is being used by all the clients.
- [ ] Get this working in a builder-less context + reimplment in the builder.

## Workspace Structure

For the sake of clarity, this is Yarn workspace structure I am proposing above:

```bash
resources/js/
│
├── admin             # Admin client (exports used by builder and dashboard)
│  ├── components     # Internal components
│  ├── context        # Context (hooks can be used by builder, dashboard, and campaign)
│  └── index.js       # webpack entry
│
├── embed             # Embed client
│  ├── components     # Internal components
│  ├── context        # Context (hooks can be used by campaign)
│  └── index.js       # webpack entry
│
├── landing           # Landing client
│  ├── components     # Internal components
│  ├── context        # Context (hooks can be used by campaign)
│  └── index.js       # webpack entry
│
├── builder           # Builder view (exports used by admin)
│  ├── components     # Internal components
│  ├── context        # Context (hooks can be used by campaign)
│  └── index.js       # Builder export
│
├── dashboard         # Dashboard view (exports used by admin)
│  ├── components     # Internal components
│  ├── context        # Internal context
│  └── index.js       # Dashboard export
│
├── campaign          # Campaign component (exports used by all clients)
│  ├── components     # Internal components
│  ├── context        # Internal context
│  └── index.js       # Campaign export
│
├── common            # Common utilities, hooks, and datasets (exports used by most packages)
│  ├── data
│  ├── hooks
│  └── utils
│
└── ui                # UI components (exports used by most packages)
   ├── admin
   ├── campaign
   └── primitives     # Primitive UI components for building other components or to be used on their own
```

**Comment by ravinderk** [comment]
@knowler everything looks good to me expect `embed` and `landing`.
Can you explain them to us more like how, who, and where we will these workspaces?

**Comment by knowler** [comment]
### Admin

The admin client is designed to be mounted within the WordPress dashboard. Further, it provides the user the ability the manage, modify, and build campaigns.

* webpack entry: `resources/js/admin/index.js`
* Bundle output: `public/js/admin.js` `public/css/admin.css`
* Estimated JS/CSS bundle size (relative to other bundles): largest
* Simplified component tree:
  ```
  Admin Shell — Builder — Campaign
             \_ Dashboard
  ```

### Landing

The purpose of the landing client is to be the public bundle that loads for the landing page that the user enabled when they built the form. On the backend, we’ll might use the REST/Rewrite API to make the route + provide the HTML (where the landing client will be mounted from). The landing client is simple and just lets the visitor view + interact with the campaign. It does not include the editing capabilities that the admin client has.

* webpack entry: `resources/js/landing/index.js`
* Bundle output: `public/js/landing.js` `public/css/landing.css`
* Estimated JS/CSS bundle size (relative to other bundles): smaller
* Simplified component tree:
  ```
  Landing Shell — Campaign
  ```

The landing shell will need to fill the entire viewport.

### Embed

The purpose of the embed client is to allow users to embed the campaign on any page they can add custom HTML to, whether or not it is on the same domain or not. The embed client is simple and just lets the visitor view + interact with the campaign. It does not include the editing capabilities that the admin client has. The embed shell might be an iframe. It basically needs to be able to be included with inline content (i.e. any page or a post).

* webpack entry: `resources/js/embed/index.js`
* Bundle output: `public/js/embed.js` `public/css/embed.css`
* Estimated JS/CSS bundle size (relative to other bundles): smaller
* Simplified component tree:
  ```
  Embed Shell — Campaign
  ```

**Comment by JasonTheAdams** [comment]
Great stuff, @knowler. Thank you for taking the time to write this up. A couple notes.

Can you please provide a time estimate for this? I see the "epic points" are 13, but I doubt that's accurate.

**Structure**
I'm wondering if it would be better to have `@givewp/campaign-admin` and `@givewp/campaign`, then leave `@givewp/components` as purely reusable components. Let `@givewp/campaign` contain all the presentational and container components unique to itself, and export the campaign component for use in the admin. It sounds perhaps like you're thinking of pulling in the presentational campaign components into the admin and piecing them together within the admin?

**Apollo Client**
I'm fine with you using this if you feel it will improve development. It certainly does a great job of handling caching for you and has a REST API wrapper. I wouldn't suggest using it for local state, though, as I think it's needlessly complex — stick to Context and hooks.

**Comment by knowler** [comment]
> Can you please provide a time estimate for this? I see the "epic points" are 13, but I doubt that's accurate.

Yes, I will estimate the time for this and report that here. I find the estimates to be a bit arbitrary. Is there a scale I can reference these from?

> **Structure**
> I'm wondering if it would be better to have @givewp/campaign-admin and @givewp/campaign, then leave @givewp/components as purely reusable components. Let @givewp/campaign contain all the presentational and container components unique to itself, and export the campaign component for use in the admin. It sounds perhaps like you're thinking of pulling in the presentational campaign components into the admin and piecing them together within the admin?

My thought was that `@givewp/campaign` would just export `<Campaign>` and then that component would be responsible for assembling itself based on a campaign object. All of the layout variations for different campaign types would also live inside `@givewp/campaign`, however, they would not be surfaced for use in other workspaces (well, you could reference them... but that’s not how they'd be intended to be accessed). For this proposed `@givewp/campaign`, (currently) there's only one way in and one way out and that's: `import Campaign from '@givewp/campaign';`. As far as how the campaign works within the builder, I was thinking that it could just detect whether or not there was a builder Context up the tree and it would become a controlled component when it does.

> **Apollo Client**
> I'm fine with you using this if you feel it will improve development. It certainly does a great job of handling caching for you and has a REST API wrapper. I wouldn't suggest using it for local state, though, as I think it's needlessly complex — stick to Context and hooks.

Sounds good, I think it will, especially for the future. For development/pre-alpha/until-we-have-working-backend, I was thinking that we could initialize the cache with static datasets of campaign objects and use local resolvers to mock the backend functionality.

**Comment by JasonTheAdams** [comment]
Got it. Help me understand the purpose of `@givewp/ui/campaign`, then. Why not just store those components within the `@givewp/campaign/components` directory? Are they accessed outside of the `Campaign` component?

**Comment by knowler** [comment]
> Help me understand the purpose of @givewp/ui/campaign, then. Why not just store those components within the @givewp/campaign/components directory? Are they accessed outside of the Campaign component?

They are not, however, it does make them a bit more easy to access with in the `@givewp/campaign` workspace, since you can just reference the package instead of the relative path. I think this is especially valuable since they will be used a lot. Also, currently, how `@givewp/components` is used within `@givewp/app` demonstrate the same advantage.

Also, since they might share common primitives with the admin UI, I think they do well in the same package. An example of this: maybe a button in the admin and in the campaign need similar capabilities, however, how they look is different. We can extract a primitive Button to `@givewp/ui/primitives` and just use the admin/campaign variations to describe how they look (or set their own defaults).

**Comment by knowler** [comment]
A lot of these workspace changes wouldn’t be necessary if nested workspaces were a thing.

**Comment by knowler** [comment]
For the sake of simplicity + to be futureproof, I’m now suggesting that we structure the `@givewp/admin` workspace like this:

```bash
resources/js/
│
├── admin             # Admin pages
│  ├── campaigns      # Campaigns page
│  │  ├── components  # Internal components
│  │  ├── views
|  │  │  ├── Builder  # (we should keep these shallow and place subcomponents within the same directory)
|  │  │  └── Manager
│  │  └── index.js    # webpack entry 
│  └── reports        # Reports page (for example)
```

**Comment by JasonTheAdams** [comment]
@knowler I like this better. I don't want to abuse the workspace system and boil it down to making import paths easier. That's certainly a nice bonus, but I prefer to think of it as organization and namespacing, so things that should be logically grouped together should be.

**Comment by knowler** [comment]
cc: @DevinWalker

Ok, so an update here. I’m most likely going to resolve this epic and any related issues in one massive PR that I already have quite a bit of progress on:

- [x] Router is implemented
- [x] Builder view is separated
- [ ] Manager view is implemented
	- [x] Header page with working "New Campaigns" button
    - [ ] Manager lists campaigns in a table
- [x] UI primitives package is created
- [x] Admin UI package is created
- [ ] The Campaign component is extracted and visibly functions on its own (new functionality, but nothing new MVP scope-wise)
- [ ] Apollo/Context API is used "in the place" of Redux.
	- [x] Context API is used for view/component specific state
	- [ ] Apollo is used for sending and retrieving data to and from the server (new functionality, but nothing new MVP scope-wise)
- [x] Final Form is implemented
	- [x] Final Form field adapter is implemented
	- [ ] Our form control components use a common API so that we can just use one field adapter

Note that a lot of this isn’t refactoring, even though refactoring is taking place in order to implement the MVP requirements.

Further explanation for why some of these steps have been taken:

<details><summary>Some definitions for clarity</summary>

* _Manager_ — the default, list view that the user is presented with when they navigate to the "Campaigns" sub-page in the Donations menu. 
    * I am open to change the name of this, but "List" seems a little too abstract and doesn’t fully communicate the capability of the user as far as their ability to manage many campaigns from a high level (i.e. create, delete, change some high-level options).
* _Builder_ — the campaign builder. This lets the user change the fine details of a single campaign.
* _Campaign_ — the component that is the campaign. 
    * This same component will be reused in various contexts such as the Builder (a part of the `admin-campaigns` client), its own landing page (a part of the `landing` client), its own `emebed` client, a Gutenberg block.
* _client_ — a self contained React app which is loaded as a part of a single PHP view. 
    * For example, the "Campaigns" sub-page loads a client called `admin-campaigns` or the "Reports" sub-page will load a client called `admin-reports` or for the public facing landing pages, a client called `landing` will be used.

</details>

<details><summary>Why are we replacing Redux?</summary>

We actually were not using Redux a ton in the first place, however, there was a lot of boilerplate for it despite that. Using the Context API is simpler since it keeps related state together and is much easier to implement (less boilerplate). Also, we aren’t really replacing it, we are just using the Context API for view/component specific state how would probably would have alongside it and then opting to use Apollo for remote data sending/retrieving (something that wasn't implemented yet). Better tools for the job — and way less files/boilerplate to do so.

</details>

<details><summary>Why are we using Final Form as a form controller?</summary>

Forms are hard and React itself doesn’t solve that outside of advising you to make sure your forms are controlled — that React is the single source of truth as far as what is the current value of a field and that only React can update it. Implementing a form controller on our own is very tedious and error-prone, so we opt to use a pre-made form controller library. Form controller libraries are great because on top of making it easy to control our form fields, they also give us great tools for field-level validation and field-level error messaging, and allow to fields to subscribe to the state of each other, which makes for a better experience on the user side (e.g. a field can adjust based on the value of another field).

Following the advice of the Give.io team, we will be using Final Form, so that we can share knowledge between projects and make maintainability easier.

**What are the implications of implementing this?**

* Reduced boilerplate per field. 👍
* We will need to make a field adapter similar to what Give.io is using and perhaps adjust some of the field components we have to follow a consistent API so that the field adapter doesn’t need to be modified per field.
    * This is great, because the Builder and the Campaign can reuse the same adapter.

</details>

<details><summary>Why are we making the Campaign its own component?</summary>

We are making the Campaign its own component so that it can function on its own in different contexts (i.e. in the Builder, on its landing page, in an emebed, in a Gutenberg block). Currently, the Campaign is built into the Builder and cannot exist on its own since:

1. There’s currently no way of referencing it for reuse.
2. The underlying logic to make it function is inseperable from the Builder.

</details>

<details><summary>What does state management look like for our app?</summary>

This is a break down of how the state management works at different levels:

* Apollo — in charge of communicating data with the server.
  * This is to be used at the top level of the client so that views can pull from the same cache.
* Context API — in charge of contextual state and holding mutated server data until it is ready to be sumbitted.
* Final Form — in charge of collecting and validating data from any forms and passing that to the Context API. It also lets us know if and when we are ready to submit.
* Prop drilling — def: simply passing data down the component tree until to gets to where it needs to go. We use this in the cases that the underlying component really doesn’t need to be getting data via a hook — which is a lot of cases.

</details>

<details><summary>Building out the Manager page</summary>

Currently, I already have the app chrome implemented for the Manager with a working "New Campaign" button.

![app-shell-header](https://user-images.githubusercontent.com/6908001/69756219-320f3980-1117-11ea-8f08-e73ff8f2ff51.gif)

_Note that in this preview the application flow isn’t what the MVP will be. I have yet to implement the new functionality where the build detects that this is a new campaign that it is editing and displays the new campaign splash first. The preview’s goal is to demonstrate that the two app header bars use a common component like the design specifies. Also, the Campaign page selector is missing since I am in the midsts of extracting the Campaign and that needs to be reworked a little to work with that._

</details>

<details><summary>Is all of this a step backwards?</summary>

Yes and no. Yes, there are a few things we need to refactor, however, this is all to help us achieve the MVP. For example, moving the router was absolutely necessary since otherwise we would not be able to implement the Manager view. Also, replacing Redux goes hand-in-hand with this change since previously, the state management was Builder-centric and even if we kept Redux, we would have started using the Context API anyway for view/component-specific state. Redux isn’t being replaced per se, it’s just not useful since app-level state doesn’t exist when we use a router. The choice to use Apollo at the app-level for sending and retrieving data to and from the server is just using a better tool for the task — a task that actually wasn’t implemented yet using Redux. Also, it aligns us with the Give.io team and their use of Apollo — except that we don’t have a GraphQL backend (yet — perhaps in the future).

</details>

All in all, I will have this all finished by the time you all get back from Thanksgiving. 🦃 Let me know if you have any questions or concerns about any of this. I wanted to send this before all of you had to go, so it might have been better written.
