### ISSUE TITLE
feat: working prototype and steps to alpha and beta release

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp-campaigns#85]
# Issue Overview

The following issue describes the items I see necessary to fulfill and working prototype of the GiveWP Campaigns project.

### Milestone 1: WordCamp US and Video Screencasts

Goals:

- Receive feedback from the community to improve project
- Drum up excitement for the new interface and features
- Display an interactive experience that Figma's prototypes doesn't

**WordCamp US 2019: November 1-3rd**

I'm looking for the following capabilities to demo during the conference:

- [ ] Introduction layout is customizable in ordering the layout, text within the heading and subheading, and I can upload a new image that's set
- [ ] The design tab can update the font styles, primary color, and max-width
- [ ] The templates screen is viewable, however does not need to be working. Just when I click on "Template" it takes me to the screen for demo purposes
- [ ] "Go Live" displays but is not functional
- [ ] I can hover over elements in the preview pane and click them to jump to the setting within the Introduction page 

Doesn't need to be done:
- Saving the campaign
- Embedding the campaign
- Interactivity on pages besides the interaction 
- Accessibility or i18n

### Milestone 2: Internal Alpha Release by March 15th, 2020

- Stripe Free and PayPal Standard payment gateways work correctly
- The "Campaigns" list screen displays and replaces "Add Form" and "All Forms" option
- Legacy forms are displayed in the new list screen
- The Campaign Type screen displays properly
- Database design is crafted and implemented for a first phase public release
- A shortcode and Gutenberg block work
- The landing page works
- Donations process properly
- Validation works properly
- Form is baseline accessible for the frontend; The admin campaign builder has MVP accessibility
- Some tests in place, not all under the sun

### Milestone 3: Beta Release on WP.org by April 15th, 2020

- Project is tested internally with bugs caught and resolved
- Basic integration with Recurring Donations as an upsell 
- Integration with Stripe Premium removes fees
- Additional tests are in place
- Promotions planned for release
- Fee Recovery is integrated
- Additional Campaign Types / Themes are configured

### Milestone 4: Merge into GiveWP Core by June 15th, 2020
 
- Feedback has been received from public via WP.org
- Codebase is ready to merge into core
- Fee Recovery is integrated
- A path to integrate Form Field Manager is being developed
- Database migrate needs are tested and ready for Core 

## Ongoing

- Videos and blog posts document our development progress for transparency and marketing purposes
- GitBook receives regular attention to document development process
